In [9]:
import numpy as np

a = np.array([20,30,40])
b = np.array([50,60,70])
c = np.array([4])

print(a)
print(b) 
print(a+b)
print(a*b)
print(a*c)

[20 30 40]
[50 60 70]
[ 70  90 110]
[1000 1800 2800]
[ 80 120 160]


In [15]:
a = np.array([10,20,"60"]) 
b = np.array([30,60,9.69]) 
print(b)
print(a)

[30.   60.    9.69]
['10' '20' '60']


In [2]:
import numpy as np

In [3]:
arr = np.array([20,30,40,50])
print(arr)
print(type(arr))

[20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
arr = np.array([[20,30,40,50],[60,70,80,90]])
print(arr)
print(arr[0:2,0:2])
print(arr[0,1:3])
print(arr[1,2:])
print(np.shape(arr))        # row , column
print(np.size(arr))         # number of array element
print(np.ndim(arr))         # number of array dimension
print(arr.dtype)            # data type of array
print(arr.astype(float))    # convet on array to a differnt type
print(arr.astype(str))
print(len(arr))             # length of array 

[[20 30 40 50]
 [60 70 80 90]]
[[20 30]
 [60 70]]
[30 40]
[80 90]
(2, 4)
8
2
int64
[[20. 30. 40. 50.]
 [60. 70. 80. 90.]]
[['20' '30' '40' '50']
 ['60' '70' '80' '90']]
2


In [5]:
arr = np.array([20,30,40,50])
print(arr[0:3])

[20 30 40]


In [6]:
arr1 = np.array([20,30,40,50])
arr2 = np.array([30,60,70,80])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(np.subtract(arr1,arr2))
print(arr1/arr2)
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))

[ 50  90 110 130]
[ 50  90 110 130]
[-10 -30 -30 -30]
[-10 -30 -30 -30]
[0.66666667 0.5        0.57142857 0.625     ]
[0.66666667 0.5        0.57142857 0.625     ]
[-8070450532247928832  1152921504606846976                    0
                    0]


In [7]:
arr1 = np.array([3,6,8,9])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 36 64 81]


In [8]:
arr1 = np.array([9, 36, 64, 81])
print(np.sqrt(arr1))


[3. 6. 8. 9.]


In [9]:
arr1 = [20,30,40,50]
arr2 = [40,50,90,70]
print(arr1+arr2)

[20, 30, 40, 50, 40, 50, 90, 70]


In [10]:
arr1 = np.array([20,30,50,60])
arr2 = np.array([40,60,30,20])
print(np.concatenate([arr1,arr2]))

[20 30 50 60 40 60 30 20]


In [11]:
arr1 = np.array([[20,30],[50,60]])
arr2 = np.array([[40,60],[30,20]])
print(np.concatenate([arr1,arr2],axis = 0))
print(np.concatenate([arr1,arr2],axis = 1))
print(np.hstack([arr1,arr2]))                 # horizontal concatenation
print(np.vstack([arr1,arr2]))                 # vertical concatenation


[[20 30]
 [50 60]
 [40 60]
 [30 20]]
[[20 30 40 60]
 [50 60 30 20]]
[[20 30 40 60]
 [50 60 30 20]]
[[20 30]
 [50 60]
 [40 60]
 [30 20]]


In [15]:
a = np.array([10,20,30,40,50,60])
#print(np.array_split(a,3))
b = np.array(np.array_split(a,3))
print(b[1])




[array([10, 20]), array([30, 40]), array([50, 60])]
[30 40]


In [10]:
a = np.array([[10,20],[30,40]])
print(np.append(a,[60,70]))

[10 20 30 40 60 70]


In [12]:
print(np.insert(a,1,[90,100],axis=1))      # arrray, index, value

[[ 10  90  20]
 [ 30 100  40]]


In [16]:
print(a)
print(np.delete(a,3))

[[10 20]
 [30 40]]
[10 20 30]


In [18]:
a = np.array([[7,3,10,22,48,2,55],[6,33,8,1,23,5,56]])
print(np.sort(a))

[[ 2  3  7 10 22 48 55]
 [ 1  5  6  8 23 33 56]]


In [29]:
a = np.array([2,4,8,3,9,1])
b = np.where(a % 2 == 0)
print(b)

(array([0, 1, 2]),)


In [31]:
a = np.array([1,2,3,4,5])
b = np.searchsorted(a,2)
print(b)

1


In [35]:
arr = np.array([20,40,30,50])
fa = arr>35
ne = arr[fa]
print(ne)

[40 50]


In [44]:
a = np.array([20,10,40,50])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

120
10
50
4
30.0
[ 20  30  70 120]
[    20    200   8000 400000]


In [64]:
a = [100,200,300,400,500,600]
b = [10,20,30,40,50,60]

price = np.array(a)
quantity = np.array(b)

#print(np.sum(price))
print(price,"\n" ,quantity)
print()
c = np.cumprod([price,quantity], axis = 0)
print(c[1].sum())


[100 200 300 400 500 600] 
 [10 20 30 40 50 60]

91000


In [77]:
import numpy as np
import statistics as stat
back_food = [2,6,1,8,4,6,9]
#[300,413,567,589,768,957,950]
arr = np.array(back_food)
print(np.mean(back_food))#sum of all the values / number of values
print(np.median(back_food))
print(stat.mode(back_food))
print(np.std(back_food))

5.142857142857143
6.0
6
2.747912008810192


In [78]:
price = [200,300,600,500]
sales = [19,17,13,18,12]
print(np.corrcoef([price,sales]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.